{
  parserUtilClass="generated.BasicParserUtil"
elementTypeClass = 'porokhin.bstruct.BasicTokenType'

 tokens = [
    OP_EQ="="
    OP_OR="|"
    OP_OPT="?"
    OP_ONEMORE="+"
    OP_ZEROMORE="*"
    OP_AND="&"
    OP_NOT="!"
    LEFT_BRACE="{"
    RIGHT_BRACE="}"
    LEFT_BRACKET="["
    RIGHT_BRACKET="]"
    LEFT_PAREN="("
    RIGHT_PAREN=")"
    DIM="dim"
    SUB="sub"
    DECLARE="declare"
    INCLUDE="include"
    AS="as"
    IF="if"
    END="end"
    EXIT="exit"

    T_INTEGER="integer"
    T_STRING="string"

    space='regexp:\s+'
    id="regexp:\w+"
    string="regexp:('([^'\\]|\\.)*'|\"([^\"\\]|\\\"|\\\'|\\)*\")"
    number="regexp:\d+"
    line_comment="regexp:'.*"
  ]
}

basicUnit ::= top*
private top ::= keyword | symbolunit
keyword ::= DIM | SUB | DECLARE | INCLUDE | AS | IF | END | EXIT
symbolunit ::= OP_EQ | OP_OR | OP_AND | LEFT_BRACKET | RIGHT_BRACKET | LEFT_PAREN | RIGHT_PAREN